// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quilti.DAL;

namespace Quilti.Migrations
{
    [DbContext(typeof(QuiltiContext))]
    [Migration("20210122063542_removeHur")]
    partial class removeHur
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Quilti.Models.Patch", b =>
                {
                    b.Property<int>("PatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatorIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("NorthPatchId")
                        .HasColumnType("int");

                    b.Property<string>("ObjectStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SouthPatchId")
                        .HasColumnType("int");

                    b.HasKey("PatchId");

                    b.HasIndex("NorthPatchId");

                    b.HasIndex("SouthPatchId");

                    b.ToTable("Patches");
                });

            modelBuilder.Entity("Quilti.Models.Patch", b =>
                {
                    b.HasOne("Quilti.Models.Patch", "NorthPatch")
                        .WithMany()
                        .HasForeignKey("NorthPatchId");

                    b.HasOne("Quilti.Models.Patch", "SouthPatch")
                        .WithMany()
                        .HasForeignKey("SouthPatchId");

                    b.Navigation("NorthPatch");

                    b.Navigation("SouthPatch");
                });
#pragma warning restore 612, 618
        }
    }
}
