// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quilti.DAL;

namespace Quilti.Migrations
{
    [DbContext(typeof(QuiltiContext))]
    partial class QuiltiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Quilti.Models.Patch", b =>
                {
                    b.Property<int>("PatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatorIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EastPatchId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("NorthPatchId")
                        .HasColumnType("int");

                    b.Property<string>("ObjectStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatchId");

                    b.HasIndex("EastPatchId")
                        .IsUnique()
                        .HasFilter("[EastPatchId] IS NOT NULL");

                    b.HasIndex("NorthPatchId")
                        .IsUnique()
                        .HasFilter("[NorthPatchId] IS NOT NULL");

                    b.ToTable("Patches");
                });

            modelBuilder.Entity("Quilti.Models.Patch", b =>
                {
                    b.HasOne("Quilti.Models.Patch", "EastPatch")
                        .WithOne("WestPatch")
                        .HasForeignKey("Quilti.Models.Patch", "EastPatchId");

                    b.HasOne("Quilti.Models.Patch", "NorthPatch")
                        .WithOne("SouthPatch")
                        .HasForeignKey("Quilti.Models.Patch", "NorthPatchId");

                    b.Navigation("EastPatch");

                    b.Navigation("NorthPatch");
                });

            modelBuilder.Entity("Quilti.Models.Patch", b =>
                {
                    b.Navigation("SouthPatch");

                    b.Navigation("WestPatch");
                });
#pragma warning restore 612, 618
        }
    }
}
